"""Modify wishlists table

Revision ID: 8079f6005212
Revises: e11a176e43a5
Create Date: 2024-08-14 13:38:04.927830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8079f6005212'
down_revision: Union[str, None] = 'e11a176e43a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('wishlists')]
    if 'movie_ids' not in columns:
        op.add_column('wishlists', sa.Column('movie_ids', sa.JSON(), nullable=True))
        
    op.drop_constraint('wishlists_ibfk_2', 'wishlists', type_='foreignkey')
    
    if 'movie_id' in columns:
        op.drop_column('wishlists', 'movie_id')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showtimes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('theater_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='showtimes_ibfk_1'),
    sa.ForeignKeyConstraint(['theater_id'], ['theaters.id'], name='showtimes_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_showtimes_id', 'showtimes', ['id'], unique=False)
    op.create_table('theaters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=26), nullable=True),
    sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='theaters_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_theaters_name', 'theaters', ['name'], unique=False)
    op.create_index('ix_theaters_id', 'theaters', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('showtime_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seat_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name='tickets_ibfk_3'),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], name='tickets_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tickets_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_tickets_id', 'tickets', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=26), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.create_table('movies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.Column('rating', mysql.FLOAT(), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('video', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('locations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('place', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_locations_id', 'locations', ['id'], unique=False)
    op.create_index('ix_locations_country', 'locations', ['country'], unique=False)
    op.create_index('ix_locations_city', 'locations', ['city'], unique=False)
    op.create_table('wishlist_movie',
    sa.Column('wishlist_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='wishlist_movie_ibfk_2'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], name='wishlist_movie_ibfk_1'),
    sa.PrimaryKeyConstraint('wishlist_id', 'movie_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movie_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='wishlists_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlists_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_wishlists_id', 'wishlists', ['id'], unique=False)
    op.create_table('movie_categories',
    sa.Column('movie_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('movie_id', 'category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('seats',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('theater_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seat_number', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('seat_type', mysql.VARCHAR(length=16), nullable=True),
    sa.ForeignKeyConstraint(['theater_id'], ['theaters.id'], name='seats_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_seats_seat_number', 'seats', ['seat_number'], unique=False)
    op.create_index('ix_seats_id', 'seats', ['id'], unique=False)
    # ### end Alembic commands ###
